# Generated by Django 5.0.2 on 2024-03-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_curso_entregable_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='fecha_entrega',
            field=models.DateTimeField(),
        ),
    ]
